version: "3"
services: 
    bot:
        restart: always
        image: $HUB_URL:$TAG
        networks: 
            - backend
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}

networks:
    backend:
        external: true
