version: "3"
services: 
    bot:
        restart: always
        image: $HUB_URL:$TAG
        network_mode: "container:pia_vpn_1"
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}

networks:
    backend:
        external: true
